Adds LVMLogicalVolume CRD and API-models
deckhouse/sds-node-configurator pull request #13
Opened 2024-01-17 09:28 UTC by ViktorKram

## Description
Adds LVMLogicalVolumeWatcher controller's CRD and API-models for further work. 
Also renamed some files for better reading.

## Why do we need it, and what problem does it solve?
It is necessary for LVM volumes manipulations. 

## What is the expected result?
New CRD added to a cluster and the controller sees the crd and able to create, update, watch and delete the resources.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-02-14 11:14 UTC, AleksZimin commented on images/agent/api/v1alpha1/lvm_logical_volume.go
> +	Status LvmLogicalVolumeStatus `json:"status,omitempty"`
```suggestion
	*Status LvmLogicalVolumeStatus `json:"status,omitempty"`
```

2024-02-14 11:14 UTC, AleksZimin commented on images/agent/api/v1alpha1/lvm_logical_volume.go
> +	Thin           ThinLogicalVolumeSpec `json:"thin"`
```suggestion
	*Thin           ThinLogicalVolumeSpec `json:"thin"`
```

2024-02-16 10:08 UTC, AleksZimin requested changes

2024-02-16 10:08 UTC, AleksZimin commented on images/agent/config/config.go
> +		args := []string{"-m", "-u", "-i", "-n", "-p", "-t", "1", "cat", "./etc/machine-id"}
```suggestion
		args := []string{"-m", "-u", "-i", "-n", "-p", "-t", "1", "cat", "/etc/machine-id"}
```

2024-02-16 14:31 UTC, dxavx approved these changes

2024-02-16 15:40 UTC, AleksZimin approved these changes

2024-02-16 15:40 UTC, merged