[controller] Fix serial discover
deckhouse/sds-node-configurator pull request #31
Opened 2024-03-18 14:27 UTC by AleksZimin

## Description

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-03-21 15:02 UTC, dxavx approved these changes

2024-03-21 23:06 UTC, apolovov requested changes

2024-03-21 23:06 UTC, apolovov commented on images/static-utils-copier/Dockerfile
> +CMD ["/static-utils", "/opt/deckhouse/sds"]
They aren't static anymore. disk-utils?

2024-03-21 23:06 UTC, apolovov commented on images/static-utils-copier/Dockerfile
>      autoconf \
images/disk-utils-installer mb?

2024-03-21 23:06 UTC, apolovov commented on images/static-utils-copier/Dockerfile
Consider using https://github.com/deckhouse/deckhouse/blob/main/tools/dev_images/additional_tools/alt/binary_replace.sh

2024-03-22 08:42 UTC, apolovov approved these changes

2024-03-22 08:46 UTC, merged